### ISSUE TITLE
Rotation matrix computation

### ISSUE THREAD

**Issue by ihaque** [pandegroup/IRMSD#1]
@leeping

Didn't you write code a while ago to get the rotation matrix out of my RMSD code? Could we reasonably integrate that into this package?

**Comment by ihaque** [comment]
ping @leeping

**Comment by kyleabeauchamp** [comment]
So I personally am not too worried about having rotation in IRMSD.  In my opinion, I'm much happier using (and maintaining) a pure-Numpy implementation of the rotation code.  It's just too hard to maintain, otherwise.

**Comment by ihaque** [comment]
hokay, closing
