### ISSUE TITLE
Mismatch between the license header and readme.

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/IRMSD#2]
The license headers in [theobald_rmsd.c](https://github.com/SimTk/IRMSD/blob/master/python/IRMSD/theobald_rmsd.c) and [rmsdcalc.c](https://github.com/SimTk/IRMSD/blob/master/python/IRMSD/rmsdcalc.c) say GPL, but the readme says BSD. Probably good to get that evened out.

**Comment by ihaque** [comment]
Assigning to @kyleabeauchamp. I'm fine either way (would prefer BSD or LGPL) for my own code, but he's the one that integrated the quartic solver, which had some other license. Can you get sign-off from the original authors for a BSD license here?

**Comment by kyleabeauchamp** [comment]
I already had to beg to get a GPL V2 exemption (theirs was V3), so BSD is probably not going to happen.  

We probably don't _need_ to use a quartic solver if we figure out a robust way to do the NR.

**Comment by kyleabeauchamp** [comment]
This is unrelated, but for your (@ihaque) reference, here is a cython wrapper of your (older version of) code.  I haven't done any benchmarks yet, however.

https://github.com/rmcgibbo/mdtraj/blob/master/MDTraj/IRMSD/rmsd_wrap.pyx

**Comment by ihaque** [comment]
> We probably don't need to use a quartic solver if we figure out a robust way to do the NR.

OK, I think this would be the best way to go. Want to give it a shot?

> cython wrapper

Nice, that's slick. I'd be in favor of ditching the pure-C wrapper and using Cython or cffi instead.

**Comment by ihaque** [comment]
PS @kyleabeauchamp : [cffi](https://cffi.readthedocs.org/en/release-0.6/) is the way to call C code from PyPy, so it would be nice to get on that train early.
